apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: slowedapp
servers: 1 
agents: 1
ports:
  # Argo CD port mapping
  - port: 11000:30080 
    nodeFilters:
      - loadbalancer 

  # Webapp port mapping
  - port: 5173:30000 
    nodeFilters:
      - loadbalancer 
  
  # default Traefik port:
  - port: 9000:9000 
    nodeFilters:
      - loadbalancer 
  
  # minioapi port:
  - port: 9005:9005 
    nodeFilters:
      - loadbalancer 

  # default HTTP port:
  - port: 80:80 
    nodeFilters:
      - loadbalancer 

  # default HTTPS port:
  - port: 443:443 
    nodeFilters:
      - loadbalancer 