---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slowed-frontend
  namespace: slowedapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  slowed-frontend
  template:
    metadata:
      labels:
        app:  slowed-frontend
    spec:
      containers:
        - name: slowed-frontend
          imagePullPolicy: Always
          image: theseanchoo/slowed-frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_SERVER_HOST
              value: "0.0.0.0" # Optional: if you use env vars in vite.config.js
            - name: VITE_PORT
              value: "5173"