---
apiVersion: argoproj.io/v1alpha1
# This is an ArgoCD Application resource definition
# It defines an application that ArgoCD will manage
# The application will be deployed to the cluster where ArgoCD is running
# The application will be sourced from a Git repository

kind: Application
metadata: 
  name: myapp 
  namespace: argocd # this has to be the same namespace as where argocd is running
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
  annotations:
    argocd-image-updater.argoproj.io/image-list: theseanchoo/slowed-frontend:~v0.1
spec:
  project: default
  source:
    repoURL: git@github.com:zexianchoo/slowedapp-src.git
    targetRevision: HEAD
    path: envs/staging/apps
  destination: # single argocd application to deploy to multiple clusters?
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true # create namespace if it does not exist
      - PrunePropagationPolicy=foreground
      - PruneLast=true