apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.external-secrets.io' 
    chart: external-secrets
    targetRevision: "0.17.0" 
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true

        # You can customize other Helm values here if needed, for example:
        # replicaCount: 1
        # serviceAccount:
        #   create: true
        #   name: "external-secrets" # Name of the service account for ESO
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: slowedapp # Namespace where ESO will be installed
  syncPolicy:
    automated:
      prune: true   
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true 