# argocd-apps/minio-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slowed-minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.min.io/'
    chart: minio
    targetRevision: 5.3.0
    helm:
      values: |
        existingSecret: "minio-credentials-secret" # The name of the K8s Secret in minio-ns

        persistence:
          enabled: true
          storageClass: "local-path"
          size: 10Gi
        service:
          type: ClusterIP
          port: 9000
        defaultBuckets:
         - name: raw-audio
         - name: processed-audio
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: slowedapp
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true 